name: Deploy Volunteam App to Expo

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          npx expo install

      - name: Log in to Expo
        run: npx expo login -u "${{ secrets.EXPO_USERNAME }}" -p "${{ secrets.EXPO_PASSWORD }}"

      - name: Publish to Expo (production)
        run: npx expo publish --non-interactive --release-channel production

      - name: Finished
        run: echo "Volunteam published to Expo successfully."
